export enum OnboardingActionTypes {
  CHANGE_NAME = 'CHANGE_NAME',
  CHANGE_PHONE = 'CHANGE_PHONE',
  CHANGE_IDENTITY_DOCUMENT_ENTITY_LIST = 'CHANGE_IDENTITY_DOCUMENT_ENTITY_LIST',

  CHANGE_MARITAL_STATUS = 'CHANGE_MARITAL_STATUS',

  CHANGE_ADDRESS = 'CHANGE_ADDRESS',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD'
}
